### ISSUE TITLE
Confusing way to add existing tracker

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/EurekaTrackerAutoPopper#10]
I should change the tracker input to take full url, the way I did it initially is just dumb.

Also, I wasn't able to copy/paste into this field so what's up with that

**Comment by electr0sheep** [comment]
Ah, I can't input / characters so probably something to do with that

**Comment by Infiziert90** [comment]
`ImGui.InputText("Instance", ref instance, 6);`

The max limit is 6, that is why full URLs not work.

**Comment by electr0sheep** [comment]
Thank you! 🙏

**Comment by electr0sheep** [comment]
I changed this to accept the full URL. I think it's much less confusing.
